### ISSUE TITLE
Bump RSpec for Tests

### ISSUE THREAD

**Issue by balasankarc** [datamapper/dm-core#283]
Hi,
Is there any specific reason why RSpec is kept at such old versions? I have seen #181  and am wondering if that is still the issue. I am trying to package dm-* gems for Debian and RSpec 1 has been out of Debian for quite some time (AFAIK, it is not available in any major OSs). So, can you please update the Tests to run using the later versions of RSpec?

**Comment by tpitale** [comment]
The project is mostly unmaintained at this point.

PRs welcome, but you'll have to keep the test matrix all running.

We don't update the tests because, for the purposes of end-users, the tests are not required to use the gem.

It may happen at some point, but it is not a small undertaking. Sorry, I cannot guarantee anything.
